Document: haproxyweb
Title: Debian haproxyweb Manual
Author: <insert document author here>
Abstract: This manual describes what haproxyweb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/haproxyweb/haproxyweb.sgml.gz

Format: postscript
Files: /usr/share/doc/haproxyweb/haproxyweb.ps.gz

Format: text
Files: /usr/share/doc/haproxyweb/haproxyweb.text.gz

Format: HTML
Index: /usr/share/doc/haproxyweb/html/index.html
Files: /usr/share/doc/haproxyweb/html/*.html
